name: Generate Acknowledgements
on:
  workflow_dispatch:
    inputs:
      eclipse-version:
        description: The version of the Eclipse-TLPs to be released. Something like '4.36'
        required: true
        type: string

permissions: {}

jobs:
  generate-acknowledgements:
    name: Generate Acknowledgements
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout Eclipse-Platform Releng Aggregator
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: eclipse-platform/eclipse.platform.releng.aggregator
        ref: master
        path: eclipse.platform.releng.aggregator
    - name: Checkout website
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: website
    - name: Collect Eclipse TLP repositories
      id: collect-repos
      working-directory: eclipse.platform.releng.aggregator
      run: |
        repos=$(git config --file .gitmodules --get-regexp '\.url$' | awk '{print $2}' | tr '\n' ' ')
        echo "repos: ${repos}"
        echo "repos=${repos}" >> "$GITHUB_OUTPUT"
    - name: Collect contributors
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          // ----------------------------------------------
          // Collect all repositories
          // ----------------------------------------------
          const submoduleURLs = '${{ steps.collect-repos.outputs.repos }}'.trim()
          console.log("Repo list is: " + submoduleURLs)
          const ghBaseURL = 'https://github.com/'
          const gitSuffix = '.git'
          const allRepos = submoduleURLs.split(' ').map(url => {
            if (!url.startsWith(ghBaseURL) || !url.endsWith(gitSuffix)) {
              core.error('Unsupported repository URL format: ' + url)
              throw new Error('Unsupported repository URL format: ' + url)
            }
            const repo = url.substring(ghBaseURL.length, url.length - gitSuffix.length)
            if (repo.split('/').length != 2) {
              throw new Error('Unsupported repository URL format: ' + url)
            }
            return repo
          })
          allRepos.unshift('eclipse-platform/eclipse.platform.releng.aggregator')
          console.log('All repositories: ' + allRepos)
          
          let [major, minor] = '${{ inputs.eclipse-version }}'.split('.')
          let previousMinor = parseInt(minor) - 1
          let lastReleaseTag = 'R' + major + '_' + previousMinor
          // ----------------------------------------------
          // Collect the contributors for each organization
          // ----------------------------------------------
          console.log("Query all commits from tag '" + lastReleaseTag + "' up to master")
          const orgaContributors = new Map()
          const contributorNames = new Map()
          const profileReplacements = new Set()
          const skippedBotAccounts = new Set()
          for (const repo of allRepos) {
            let [organization, repository] = repo.split('/')
            let contributors = computeIfAbsent(orgaContributors, organization, () => new Set())
            console.log("Query for organization '" + organization + "' repository '" + repository + "'" )
            // See https://octokit.github.io/rest.js/v21/#repos-compare-commits-with-basehead
            // About pagination, see https://github.com/octokit/octokit.js#pagination
            let responseIterator = github.paginate.iterator(github.rest.repos.compareCommitsWithBasehead, {
              owner: organization, repo: repository,
              basehead: lastReleaseTag + '...master',
              per_page: 200,
            })
            let commitCount = 0
            for await (const response of responseIterator) { // iterate through each response
              for (const commitData of response.data.commits) {
                console.log(commitData)
                let authorName = commitData.commit.author.name
                if (commitData.author) {
                  let profile = commitData.author.login
                  if (isBotEmail(commitData.commit.author.email)) { // Exclude contributors from bot-accounts
                    skippedBotAccounts.add(profile)
                    continue;
                  }
                  const committerProfile = commitData.committer?.login
                  if (commitData.commit.author.name == commitData.commit.committer.name 
                        && committerProfile && profile != committerProfile) {
                    // Sometimes contributors use different profiles. Let the committer profile take precedence
                    profileReplacements.add(profile + "->" + committerProfile)
                    profile = committerProfile
                  }
                  contributors.add(profile)
                  computeIfAbsent(contributorNames, profile, () => new Set()).add(authorName)
                } else { // author is null for directly pushed commits, which happens e.g. for I-build submodule updates
                  console.log('Skip commit of ' + authorName)
                }
                commitCount++
              }
            }
            console.log('Processed commits: ' + commitCount)
          }
          
          // ------------------------------------------------------
          // Select name if multiple have been found for one contributor
          // ------------------------------------------------------
          const selectedContributorNames = new Map()
          for (const [profile, names] of contributorNames) {
            if (names.size > 1) {
              console.log("Multiple names encountered for " + profile + ": " + Array.from(names).join(', '))
            }
            // Select longest name, assuming that's correct
            let selectedName = [...names].reduce((n1, n2) => n1.length > n2.length ? n1 : n2)
            selectedContributorNames.set(profile, selectedName)
          }
          const orgaContributorEntries = new Map()
          for (const [organization, contributors] of orgaContributors) {
            const contributorEntries = Array.from(contributors, profile => {
              const name = selectedContributorNames.get(profile)
              if (!name) {
                 throw new Error('No selected name for profile: ' + profile)
              }
              return [name, profile]
            })
            contributorEntries.sort((e1, e2) => e1[0].localeCompare(e2[0]))
          }
          
          // ------------------------------------------------------
          // Insert the list of contributors into the template file
          // ------------------------------------------------------
          const fs = require('fs')
          const acknowledgementsFile = 'website/news/${{ inputs.eclipse-version }}/acknowledgements.md'
          let lines = fs.readFileSync(acknowledgementsFile, {encoding: 'utf8'}).split(/\r?\n/)
          for (const [organization, contributors] of orgaContributors) {
            console.log('Insert contributors of ' + organization)
            const startMarker = lines.indexOf('<!-- START: ' + organization + ' contributors -->')
            const endMarker   = lines.indexOf('<!-- END:   ' + organization + ' contributors -->')
            if (startMarker < 0 || endMarker < 0) {
              throw new Error('Start or end marker to found for organization: ' + organization)
            }
            const contributorEntries = []
            for (const contributorProfile of contributors) {
              const name = selectedContributorNames.get(contributorProfile)
              if (!name) {
                 throw new Error('No selected name for profile: ' + contributorProfile)
              }
              contributorEntries.push([name, contributorProfile])
            }
            // Sort by name in ascending order
            contributorEntries.sort((e1, e2) => e1[0].localeCompare(e2[0]))
            
            lines.splice(startMarker + 1, endMarker - (startMarker + 1), ...Array.from(contributorEntries, ([name, profileId]) => {
              return '- [' + name + '](' + ghBaseURL + profileId + ')'
            }))
          }
          // Update last-revised date
          const lastRevisedLineIndex = lines.findIndex(l => l.startsWith('Last revised: '))
          lines[lastRevisedLineIndex] = 'Last revised: ' + new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })
          fs.writeFileSync(acknowledgementsFile, lines.join('\n'), {encoding: 'utf8'})
          
          //TODO: add this to the PR message as well as omitted bot accounts?!
          console.log("Profile replacements: " + Array.from(profileReplacements).join(', '))
          console.log("Skipped bots: " + Array.from(skippedBotAccounts).join(', '))
          
          function isBotEmail(email) {
            return email.endsWith("-bot@eclipse.org") || email.endsWith("[bot]@users.noreply.github.com")
          }
          
          function computeIfAbsent(map, key, valueSupplier) {
            let value = map.get(key)
            if (!value) {
              value = valueSupplier()
              map.set(key, value)
            }
            return value
          }
          
          // TODO: consider coauthors/also-by?
    - name: Create Acknowledgements for Release ${{ github.event.milestone.title }}
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        path : website
        author: Eclipse Releng Bot <eclipse-releng-bot@eclipse.org>
        commit-message: Update Acknowledgements for ${{ inputs.eclipse-version }}
        branch: acknowledgements_${{ inputs.eclipse-version }}
        title: Update Acknowledgements for ${{ inputs.eclipse-version }}
        body: |
          Update the list of contributors in the Acknowledgements for ${{ inputs.eclipse-version }}.
        delete-branch: true
